### ISSUE TITLE
Set the database name with the credentials

### ISSUE THREAD

**Issue by MaximeHollebecq** [med-material/ArduinoLogger#19]
Actually , the database name selected for MySQL upload is set by the label on the arduino firmware by the label.
![image](https://user-images.githubusercontent.com/23449138/70525629-127d0580-1b48-11ea-8baf-ead844091828.png)

the idea is to use the database name in the credentials istead of the firmware.

**Comment by bastianilso** [comment]
good idea - yes, this is a remnant hack from the old system, feel free to change this. nice find 🍍
