### ISSUE TITLE
mac error "unknown column TimeStamp" - new release needed?

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/ArduinoLogger#32]
On a MAC when trying to publish logs to the server I get the below error.
I think we might have changed the table structure and the MAC release didn't get updated.
![image](https://user-images.githubusercontent.com/1982879/77092869-81e97780-6a0a-11ea-82d3-094750dbcb22.png)

**Comment by bastianilso** [comment]
The issue was in the database - we had no column for collecting timestamps for EDAIBI-Serial data. I added the column now. Could you try again?

**Comment by hendrikknoche** [comment]
one more field missing :-)
![image](https://user-images.githubusercontent.com/1982879/77144653-be5ab900-6a86-11ea-877f-2dee814bc324.png)

**Comment by bastianilso** [comment]
Did you add it yourself? I can see there is a column called Millis inside the database.

**Comment by hendrikknoche** [comment]
Hmm, strange. I think I might have added it at some point but it still throws the error

best

Hendrik

--
Hendrik Knoche
Department of Architecture, Design & Media Technology
Rendsburggade 14, 5-341
9200 Aalborg SV, DK

t: +45 8238 9438
m: +45 6051 3546

**Comment by hendrikknoche** [comment]
it seems the error is on the database side, right?

**Comment by bastianilso** [comment]
@hendrikknoche could you save it to CSV and upload it to this thread?
very peculiar, cause we do have the column there,..
`[Fri Mar 20 08:41:52.229286 2020] [:error] [pid 39339] [client 172.29.53.237:65462] prepare() failed: Unknown column 'Millis' in 'field list'`

**Comment by hendrikknoche** [comment]
here it is... it's the email most likely

Email;Millis;EDA;IBI;RawPulse;Pressure;Button
;
2020-03-20 11:48:18;hk@create.aau.dk;1;1;1857;0;0;81;0;0;
2020-03-20 11:48:18;hk@create.aau.dk;1;1;1867;4;0;80;0;0;
2020-03-20 11:48:18;hk@create.aau.dk;1;1;1878;0;0;81;0;0;
2020-03-20 11:48:18;hk@create.aau.dk;1;1;1888;4;0;81;0;0;
2020-03-20 11:48:18;hk@create.aau.dk;1;1;1898;0;1894;80;0;0;

**Comment by bastianilso** [comment]
Could you upload the CSV file itself? as an attachment (drag n drop)? sorry, i need to be sure I understand what is in what column

**Comment by hendrikknoche** [comment]
[RTIIlog.csv.zip](https://github.com/med-material/ArduinoLogger/files/4359258/RTIIlog.csv.zip)

**Comment by bastianilso** [comment]
![image](https://user-images.githubusercontent.com/3967945/77161934-160b1b80-6aab-11ea-916b-844d5978cc5d.png)

It looks to me like there is something wrong with the output here + some minor unrelated issues:
- When exporting to CSV files, the ArduinoLogger does not insert a "TimeStamp" value in the header for column 1 (however, this is not a problem for DB logging, thats for sure).
- All columns except "E-mail" column, seem to be mismatched to their header.
- There is a surplus of columns, compared to headers.

The problem we see with columns mismatching/being too many, is likely the source of the DB logging problem. I have updated our php file with some extra debug logging.
Could I ask you to do the following:

- Remove any "coldump" and "logdump" files present inside `~/Library/Application Support/AAU/ArduinoLogger/Data` (alternatively, try Ctrl+F for coldump/logdump on your Mac and remove any that appears).
- Open Arduino IDE and inside it, the Serial Monitor, then check that there are only 6 columns present in the output?
- Open the ArduinoLogger software, record some data, try to publish it, save as CSV and upload the CSV here?

Then i will make a comparison and see what is happening. If all of this goes wrong, we might want to try some remote-control over MS teams and debugging in Unity.

**Comment by hendrikknoche** [comment]
let's do a screen share call around this. I cannot find that directory (after AAU it goes to RTII and there's no Data subdir). I'm getting another error 
![image](https://user-images.githubusercontent.com/1982879/77185734-2b477080-6ad2-11ea-8fc4-7dc8ab924389.png) PID this time.
Was I supposed to DL a new ino or dmg file?
[log.csv.zip](https://github.com/med-material/ArduinoLogger/files/4360819/log.csv.zip)

**Comment by bastianilso** [comment]
It seems like the main issue was the missing `PID` column in the database. The database uploading works now.
